### ISSUE TITLE
Make build platform independent

### ISSUE THREAD

**Issue by yaziza** [yaziza/botanj#1]
Botanj is currently building only on MacOS machines, and requires building native Botan. This is causing the travis CI [build](https://travis-ci.com/github/yaziza/botanj) to fail.

We should provide compiled libs (`src/main/resources/native/{winods|macos|linux}`) and use the right lib on runtime after OS detection.

**Comment by securitykernel** [comment]
I wouldn't ship compiled libs with this package. Botan is highly configurable and some users may want to bring their own config, e.g., built with the BSI module policy in the context of VS-NfD development.

For standard configurations, users can still install Botan using their package manager of choice, e.g., apt on Ubuntu and Homebrew on macOS. jnr-ffi is able to figure out the system library path on its own, e.g., by looking up /etc/ld.conf.so*. Changing

`result = NATIVE = LibraryLoader.create(BotanNative.class).load(libPath);`

to

`result = NATIVE = LibraryLoader.create(BotanNative.class).load("botan-2");`

did the trick for me on Ubuntu 20.04 and macOS Catalina. For Windows, I don't know, and couldn't test, because I have no Windows test environment currently.

If Travis provides a Botan version that is too old, you can still build it from source.

**Comment by yaziza** [comment]
@securitykernel Thank you so much for your support ! The build is now green  :)
